// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq3G0PeisOrjs3Td6u4JOdQqwIstMucjE',
    appId: '1:1063290859150:android:df209cad20b3704e4923df',
    messagingSenderId: '1063290859150',
    projectId: 'monsterprojectteam-onyx-27a7d',
    storageBucket: 'monsterprojectteam-onyx-27a7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkqqLNlHIidJgHcXc9FSPlpgaRxwDjasQ',
    appId: '1:1063290859150:ios:9ccef79046f1c81c4923df',
    messagingSenderId: '1063290859150',
    projectId: 'monsterprojectteam-onyx-27a7d',
    storageBucket: 'monsterprojectteam-onyx-27a7d.appspot.com',
    iosClientId: '1063290859150-rb8p3kieo7rdcbk17dc8496kt0v5oojf.apps.googleusercontent.com',
    iosBundleId: 'com.example.monster',
  );
}
